name: Build database docs

on:
  push:
    branches:
      - master
    paths:
      - 'schema/*.dbml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14 (LTS)
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm install -g dbdocs
    
    - name: Update database documentation
      env:
        DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
    - run: dbdocs build ./schema/randomicu.dbml
